#!/bin/bash
this_dir="$PWD"
if [ -f $HOME/.zshrc ]; then
  mv --backup=numbered  $HOME/.zshrc $HOME/.zshrc.bku
fi
if [ -L $HOME/.zshrc ]; then
  rm $HOME/.zshrc
fi
ln -s $this_dir/zsh/.zshrc $HOME/.zshrc
cd config
./make_config_symlinks

