#!/bin/bash
this_dir="$PWD"
for rcfile in .zshrc .zsh-completions-rc .zsh-paths; do
  #if the file exists, move it to a backup
  [[ -f $HOME/$rcfile ]] && mv --backup=numbered $HOME/$rcfile $HOME/$rcfile.bku
  #if a symlink exists, move it to a backup but indicate it was a link (not sure -f won't fire already, we will see, lol)
  [[ -L $HOME/$rcfile ]] && mv --backup=numbered $HOME/$rcfile $HOME/$rcfile.symlink.bku
  ln -s $this_dir/zsh/$rcfile $HOME/$rcfile
done

cd config
./make_config_symlinks

