#!/bin/bash
this_dir="$PWD"
ignore_list=".git .gitignore README.md make_config_symlinks"
#SIMPLE_BACKUP_SUFFIX=".1"
cd $HOME/.config
pwd
for i in `ls -A $this_dir`; do
  if [[ $ignore_list != *$i* ]]; then
    [[ -f $HOME/.config/$i ]] && echo "moving:$HOME/.config/$i" &&  mv --backup=numbered $HOME/.config/$i $HOME/.config/$i.bku 
    [[ -L $HOME/.config/$i ]] && echo "cannot backup directory simlinks... i don't understand this weird shit its doing, I'd like to, but its not worth my time at the moment!" && rm -f $HOME/.config/$i 
    echo "creating symlink from $HOME/.config/$i --->  $this_dir/$i"
    ls -al $HOME/.config | grep boxes
    rm -f $HOME/.config/$i && ln -s $this_dir/$i  $HOME/.config/$i
  fi
done
if [[ $1 == "--remove-backups" ]]; then
  if [[ $2 == "all" ]]; then
    backup_suffix="*"
  else
    backup_suffix='.\~'
  fi
  for i in `ls -A`; do
    if [[ $ignore_list != *$i* ]]; then
      rm -f $HOME/.config/$i.bku$backup_suffix
      rm -f $HOME/.config/$i.symlink.bku$backup_suffix
    fi
  done;
fi

cd $this_dir

