#!/bin/bash
this_dir="$PWD"
for i in `ls -A`; do
  if [ $i != ".git" ] && [ $i != ".gitignore" ] && [ $i != "README.md" ] && [ $i != "make_config_symlinks" ]; then
      rm -rf $HOME/.config/$i
      ln -s $this_dir/$i  $HOME/.config/$i
  fi
done

